sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
  break_beam_2:
    type: break_beam
    pose:
      xyz: [1.6, -0.5,0.91]
      rpy: [0, 0, 'pi']
  Camera_Extra:
    type: logical_camera
    pose:
      xyz: [-0.3, 0, 1.72]
      rpy: [0, 'pi/2', 0]
  Camera_bins_links:
    type: logical_camera
    pose:
      xyz: [-0.3,1.53,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_bins_rechts:
    type: logical_camera
    pose:
      xyz: [-0.3,-1.53,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_converyor_links:
    type: logical_camera
    pose:
      xyz: [1.3, 1.74,1.86]
      rpy: [0, 'pi/2', 0]
  Camera_converyor_Rechts:
    type: logical_camera
    pose:
      xyz: [1.3, -1.0, 1.86]
      rpy: [0, 'pi/2', 0]
  Camera_AGV_Links:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  Camera_AGV_Rechts:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.5]
      rpy: [0, 'pi/2', 0]

