sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
  break_beam_2:
    type: break_beam
    pose:
      xyz: [1.6, -0.5,0.91]
      rpy: [0, 0, 'pi']
  Camera_Bin_1:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.916, 1.72]
      rpy: [0, 'pi/2', 0]
  Camera_Bin_2:
    type: logical_camera
    pose:
      xyz: [-0.3,1.15,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_Bin_3:
    type: logical_camera
    pose:
      xyz: [-0.3,0.383,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_Bin_4:
    type: logical_camera
    pose:
      xyz: [-0.3,-0.383,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_Bin_5:
    type: logical_camera
    pose:
      xyz: [-0.3,-1.15,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_Bin_6:
    type: logical_camera
    pose:
      xyz: [-0.3,-1.916,1.72]
      rpy: [0, 'pi/2', 0]
  Camera_Converyor_Links:
    type: logical_camera
    pose:
      xyz: [1.3, 1.74,1.86]
      rpy: [0, 'pi/2', 0]
  Camera_Converyor_Rechts:
    type: logical_camera
    pose:
      xyz: [1.3, -1.0, 1.86]
      rpy: [0, 'pi/2', 0]
  Camera_AGV_Links:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  Camera_AGV_Rechts:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.5]
      rpy: [0, 'pi/2', 0]

